# Generated by Django 5.2.8 on 2025-11-29 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_category_author_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
